@startuml
'https://plantuml.com/state-diagram
title D-Day 상태 다이어그램
scale 500 width

[*] --> NotShooting

state NotShooting {
  [*] --> Idle
  Idle --> Configuring : EvConfig
  Configuring --> Idle : EvConfig
}

state Configuring {
  [*] --> NewValueSelection
  NewValueSelection --> NewValuePreview : EvNewValue
  NewValuePreview --> NewValueSelection : EvNewValueRejected
  NewValuePreview --> NewValueSelection : EvNewValueSaved

  state NewValuePreview {
     State1 -> State2
  }
}
[*] ---> CreateDDay
[*] ---> RetrieveDDay
[*] ---> UpdateDDay
[*] ---> DeleteDDay
CreateDDay --> [*]
RetrieveDDay --> [*]
UpdateDDay --> [*]
DeleteDDay --> [*]
state CreateDDay
state RetrieveDDay
state UpdateDDay
state DeleteDDay
@enduml